### ISSUE TITLE
Cancel account David Fountaine | Creation Technology

### ISSUE THREAD

**Issue by vicomat** [keymetrics/keymetrics-api#19]
Hello

This is David Fountaine from Creation Technology Solutions.

I noticed recently that we are paying for an old Keymetrics account that we are not using & belonged to an ex employee for an old Project. I want to cancel the monthly payment but I do not have the account details associated with the payment account.

Please let me know how we cancel this payment?

The card associated with the account is an American Express card finishing 32002

The last payment taken was on 1st July 2017 for 29 USD & I can see a payment reference of AT171820028000010482759

Please let me know asap.

Thanks

David

**Comment by vmarchaud** [comment]
Need a grunt script to call [Bucket.transfer](https://github.com/keymetrics/km-api/blob/master/models/Bucket.js#L507) from a command like this : `grunt bucket:transfer:<username>:<username>`

**Comment by vmarchaud** [comment]
Issue moved to [keymetrics/km-api #301](https://github.com/keymetrics/km-api/issues/301) via [**ZenHub**](https://www.zenhub.com/)
